// <auto-generated />
using System;
using Event.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Event.Data.Migrations
{
    [DbContext(typeof(EventDbContext))]
    [Migration("20260626103458_UpdateModelChanges")]
    partial class UpdateModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Event.Models.Admin", b =>
                {
                    b.Property<string>("Admin_Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password_Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password_Reset_Token")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Admin_Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Event.Models.AdminAction", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActionId"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("ActionId"), 10000L, null, null, null, null, null);

                    b.Property<string>("ActionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TicketId")
                        .HasColumnType("integer");

                    b.HasKey("ActionId");

                    b.HasIndex("AdminId");

                    b.HasIndex("TicketId");

                    b.ToTable("AdminActions");
                });

            modelBuilder.Entity("Event.Models.Booking", b =>
                {
                    b.Property<int>("Booking_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Booking_Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Booking_Id"), 10000L, null, null, null, null, null);

                    b.Property<int>("Attendee_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Booking_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CheckIn_Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Event_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Qr_Code_Path")
                        .HasColumnType("text");

                    b.Property<string>("Qr_Secret_Hash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Virtual_Url")
                        .HasColumnType("text");

                    b.HasKey("Booking_Id");

                    b.HasIndex("Attendee_Id");

                    b.HasIndex("Event_Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Event.Models.BookingDetail", b =>
                {
                    b.Property<int>("Booking_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Tier_Name")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Booking_Id", "Tier_Name");

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("Event.Models.BookingPayment", b =>
                {
                    b.Property<int>("Booking_Payment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Booking_Payment_Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Booking_Payment_Id"), 10000L, null, null, null, null, null);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Booking_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payment_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Platform_Fee_Cut")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Transaction_Id")
                        .HasColumnType("bigint");

                    b.HasKey("Booking_Payment_Id");

                    b.HasIndex("Booking_Id");

                    b.HasIndex("Transaction_Id");

                    b.ToTable("BookingPayments");
                });

            modelBuilder.Entity("Event.Models.Event", b =>
                {
                    b.Property<int>("Event_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Event_Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Event_Id"), 10000L, null, null, null, null, null);

                    b.Property<string>("Age_Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("ALL");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("Date_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Duration_Hours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Event_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image_Url")
                        .HasColumnType("text");

                    b.Property<int>("Organizer_Id")
                        .HasColumnType("integer");

                    b.Property<bool>("Requires_Staff")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Venue_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Virtual_Password_Hash")
                        .HasColumnType("text");

                    b.Property<string>("Virtual_Url")
                        .HasColumnType("text");

                    b.HasKey("Event_Id");

                    b.HasIndex("Organizer_Id");

                    b.HasIndex("Venue_Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Event.Models.EventFeedback", b =>
                {
                    b.Property<int>("Feedback_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Feedback_Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Feedback_Id"), 10000L, null, null, null, null, null);

                    b.Property<int>("Attendee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Event_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Feedback_Id");

                    b.HasIndex("Attendee_Id");

                    b.HasIndex("Event_Id");

                    b.ToTable("EventFeedbacks");
                });

            modelBuilder.Entity("Event.Models.EventReport", b =>
                {
                    b.Property<int>("Report_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Report_Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Report_Id"), 10000L, null, null, null, null, null);

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Event_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Reporter_Id")
                        .HasColumnType("integer");

                    b.Property<string>("ResponseAction")
                        .HasColumnType("text");

                    b.HasKey("Report_Id");

                    b.HasIndex("Event_Id");

                    b.HasIndex("Reporter_Id");

                    b.ToTable("EventReports");
                });

            modelBuilder.Entity("Event.Models.EventStaffAllocation", b =>
                {
                    b.Property<int>("Event_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("integer");

                    b.HasKey("Event_Id", "Employee_ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("EventStaffAllocations");
                });

            modelBuilder.Entity("Event.Models.EventTicketTier", b =>
                {
                    b.Property<int>("Event_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Tier_Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tickets_Sold")
                        .HasColumnType("integer");

                    b.HasKey("Event_Id", "Tier_Name");

                    b.ToTable("EventTicketTiers");
                });

            modelBuilder.Entity("Event.Models.Notification", b =>
                {
                    b.Property<int>("Notification_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Notification_Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Notification_Id"), 10000L, null, null, null, null, null);

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("MessageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Recipient_Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Retry_Count")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Sent_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Notification_Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Event.Models.OrganizerPayout", b =>
                {
                    b.Property<int>("Payout_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Payout_Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Payout_Id"), 10000L, null, null, null, null, null);

                    b.Property<int>("Event_Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Payout_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Payout_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Platform_Commission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Processed_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Total_Ticket_Sales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("Transaction_Id")
                        .HasColumnType("bigint");

                    b.HasKey("Payout_Id");

                    b.HasIndex("Event_Id");

                    b.HasIndex("Transaction_Id");

                    b.ToTable("OrganizerPayouts");
                });

            modelBuilder.Entity("Event.Models.OrganizerUpfrontPayment", b =>
                {
                    b.Property<int>("Upfront_Payment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Upfront_Payment_Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Upfront_Payment_Id"), 10000L, null, null, null, null, null);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Event_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Payment_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Transaction_Id")
                        .HasColumnType("bigint");

                    b.HasKey("Upfront_Payment_Id");

                    b.HasIndex("Event_Id");

                    b.HasIndex("Transaction_Id");

                    b.ToTable("OrganizerUpfrontPayments");
                });

            modelBuilder.Entity("Event.Models.PlatformSettings", b =>
                {
                    b.Property<int>("Settings_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Settings_Id"));

                    b.Property<int>("Max_Tickets_Per_Booking")
                        .HasColumnType("integer");

                    b.Property<decimal>("Physical_Event_Activation_Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Staff_Flat_Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ticket_Commission_Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ticket_Fixed_Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Updated_By_Admin_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Virtual_Event_Activation_Fee")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Settings_Id");

                    b.HasIndex("Updated_By_Admin_Id");

                    b.ToTable("PlatformSettings");
                });

            modelBuilder.Entity("Event.Models.Region", b =>
                {
                    b.Property<string>("Region_Id")
                        .HasColumnType("text");

                    b.Property<int>("No_Of_Staffs")
                        .HasColumnType("integer");

                    b.Property<string>("Region_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Region_Id");

                    b.ToTable("Management");
                });

            modelBuilder.Entity("Event.Models.Staff", b =>
                {
                    b.Property<int>("Employee_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Employee_ID"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Employee_ID"), 10000L, null, null, null, null, null);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAllocated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Employee_ID");

                    b.HasIndex("Region_Id");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("Event.Models.SupportTicket", b =>
                {
                    b.Property<int>("Ticket_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Ticket_Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Ticket_Id"), 10000L, null, null, null, null, null);

                    b.Property<string>("ConcernUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EsclationStatus")
                        .HasColumnType("text");

                    b.Property<int?>("RelatedId")
                        .HasColumnType("integer");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer");

                    b.HasKey("Ticket_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("Event.Models.TermsAndConditions", b =>
                {
                    b.Property<string>("Terms_Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("File_Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Terms_Id");

                    b.ToTable("TermsAndConditions");
                });

            modelBuilder.Entity("Event.Models.Transaction", b =>
                {
                    b.Property<long>("Transaction_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Transaction_Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<long>("Transaction_Id"), 1000000000000000L, null, null, null, null, null);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payment_Method_Details")
                        .HasColumnType("text");

                    b.Property<string>("Receiver_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Refunded_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Related_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Sender_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transaction_Reference")
                        .HasColumnType("text");

                    b.Property<string>("Transaction_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Event.Models.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("User_Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("User_Id"), 10000L, null, null, null, null, null);

                    b.Property<string>("Consented_Terms_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Has_Marketing_Consent")
                        .HasColumnType("boolean");

                    b.Property<string>("Mobile_Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password_Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password_Reset_Token")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TermsAndConditionsTerms_Id")
                        .HasColumnType("text");

                    b.HasKey("User_Id");

                    b.HasIndex("TermsAndConditionsTerms_Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Event.Models.UserInterestedRegion", b =>
                {
                    b.Property<int>("User_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Region_Id")
                        .HasColumnType("text");

                    b.HasKey("User_Id", "Region_Id");

                    b.HasIndex("Region_Id");

                    b.ToTable("UserInterestedRegions");
                });

            modelBuilder.Entity("Event.Models.Venue", b =>
                {
                    b.Property<int>("Venue_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Venue_Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Venue_Id"), 10000L, null, null, null, null, null);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Hourly_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Is_Available")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Venue_Id");

                    b.HasIndex("Region_Id");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("Event.Models.VenueSeatCapacity", b =>
                {
                    b.Property<int>("Venue_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Tier_Name")
                        .HasColumnType("text");

                    b.Property<int>("Total_Seats")
                        .HasColumnType("integer");

                    b.HasKey("Venue_Id", "Tier_Name");

                    b.ToTable("VenueSeatCapacities");
                });

            modelBuilder.Entity("Event.Models.AdminAction", b =>
                {
                    b.HasOne("Event.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Event.Models.SupportTicket", "SupportTicket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Admin");

                    b.Navigation("SupportTicket");
                });

            modelBuilder.Entity("Event.Models.Booking", b =>
                {
                    b.HasOne("Event.Models.User", "Attendee")
                        .WithMany("Bookings")
                        .HasForeignKey("Attendee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Event.Models.Event", "Event")
                        .WithMany("Bookings")
                        .HasForeignKey("Event_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Event.Models.BookingDetail", b =>
                {
                    b.HasOne("Event.Models.Booking", "Booking")
                        .WithMany("Details")
                        .HasForeignKey("Booking_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Event.Models.BookingPayment", b =>
                {
                    b.HasOne("Event.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("Booking_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Event.Models.Transaction", "Transaction")
                        .WithMany("BookingPayments")
                        .HasForeignKey("Transaction_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Event.Models.Event", b =>
                {
                    b.HasOne("Event.Models.User", "Organizer")
                        .WithMany("OrganizedEvents")
                        .HasForeignKey("Organizer_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Event.Models.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("Venue_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organizer");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Event.Models.EventFeedback", b =>
                {
                    b.HasOne("Event.Models.User", "Attendee")
                        .WithMany("Feedbacks")
                        .HasForeignKey("Attendee_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Event.Models.Event", "Event")
                        .WithMany("Feedbacks")
                        .HasForeignKey("Event_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Event.Models.EventReport", b =>
                {
                    b.HasOne("Event.Models.Event", "Event")
                        .WithMany("Reports")
                        .HasForeignKey("Event_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Event.Models.User", "Reporter")
                        .WithMany("Reports")
                        .HasForeignKey("Reporter_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("Event.Models.EventStaffAllocation", b =>
                {
                    b.HasOne("Event.Models.Staff", "Staff")
                        .WithMany("EventAllocations")
                        .HasForeignKey("Employee_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Event.Models.Event", "Event")
                        .WithMany("StaffAllocations")
                        .HasForeignKey("Event_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Event.Models.EventTicketTier", b =>
                {
                    b.HasOne("Event.Models.Event", "Event")
                        .WithMany("TicketTiers")
                        .HasForeignKey("Event_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Event.Models.OrganizerPayout", b =>
                {
                    b.HasOne("Event.Models.Event", "Event")
                        .WithMany("Payouts")
                        .HasForeignKey("Event_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Event.Models.Transaction", "Transaction")
                        .WithMany("Payouts")
                        .HasForeignKey("Transaction_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Event");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Event.Models.OrganizerUpfrontPayment", b =>
                {
                    b.HasOne("Event.Models.Event", "Event")
                        .WithMany("UpfrontPayments")
                        .HasForeignKey("Event_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Event.Models.Transaction", "Transaction")
                        .WithMany("UpfrontPayments")
                        .HasForeignKey("Transaction_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Event.Models.PlatformSettings", b =>
                {
                    b.HasOne("Event.Models.Admin", "UpdatedByAdmin")
                        .WithMany("UpdatedSettings")
                        .HasForeignKey("Updated_By_Admin_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UpdatedByAdmin");
                });

            modelBuilder.Entity("Event.Models.Staff", b =>
                {
                    b.HasOne("Event.Models.Region", "Region")
                        .WithMany("Staffs")
                        .HasForeignKey("Region_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Event.Models.SupportTicket", b =>
                {
                    b.HasOne("Event.Models.User", "User")
                        .WithMany("SupportTickets")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Event.Models.User", b =>
                {
                    b.HasOne("Event.Models.TermsAndConditions", null)
                        .WithMany("ConsentedUsers")
                        .HasForeignKey("TermsAndConditionsTerms_Id");
                });

            modelBuilder.Entity("Event.Models.UserInterestedRegion", b =>
                {
                    b.HasOne("Event.Models.Region", "Region")
                        .WithMany("InterestedUsers")
                        .HasForeignKey("Region_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Event.Models.User", "User")
                        .WithMany("InterestedRegions")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Event.Models.Venue", b =>
                {
                    b.HasOne("Event.Models.Region", "Region")
                        .WithMany("Venues")
                        .HasForeignKey("Region_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Event.Models.VenueSeatCapacity", b =>
                {
                    b.HasOne("Event.Models.Venue", "Venue")
                        .WithMany("SeatCapacities")
                        .HasForeignKey("Venue_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Event.Models.Admin", b =>
                {
                    b.Navigation("UpdatedSettings");
                });

            modelBuilder.Entity("Event.Models.Booking", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Event.Models.Event", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Feedbacks");

                    b.Navigation("Payouts");

                    b.Navigation("Reports");

                    b.Navigation("StaffAllocations");

                    b.Navigation("TicketTiers");

                    b.Navigation("UpfrontPayments");
                });

            modelBuilder.Entity("Event.Models.Region", b =>
                {
                    b.Navigation("InterestedUsers");

                    b.Navigation("Staffs");

                    b.Navigation("Venues");
                });

            modelBuilder.Entity("Event.Models.Staff", b =>
                {
                    b.Navigation("EventAllocations");
                });

            modelBuilder.Entity("Event.Models.TermsAndConditions", b =>
                {
                    b.Navigation("ConsentedUsers");
                });

            modelBuilder.Entity("Event.Models.Transaction", b =>
                {
                    b.Navigation("BookingPayments");

                    b.Navigation("Payouts");

                    b.Navigation("UpfrontPayments");
                });

            modelBuilder.Entity("Event.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Feedbacks");

                    b.Navigation("InterestedRegions");

                    b.Navigation("OrganizedEvents");

                    b.Navigation("Reports");

                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("Event.Models.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("SeatCapacities");
                });
#pragma warning restore 612, 618
        }
    }
}
